
name: Deploy
on:  
  push:
      branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host : ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script:
            cd Tests
            git clone https://github.com/YaroslavKSE/Tests.git
            flask --app api run --host=0.0.0.0 --port=80
            echo "Deployment to Digital ocean was successfull"

